replicaCount: 2

image:
  repository: nginx
  tag: "1.23"
  pullPolicy: IfNotPresent

service:
  nodePort: 30081

rollout:
  strategy: canary
  autoPromotionEnabled: true
  steps:
    - setWeight: 25
    - pause: {duration: 15s}
    - setWeight: 50
    - pause: {duration: 15s}
    - setWeight: 100
