replicaCount: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: NodePort
  nodePort: 30081

rollout:
  strategy: canary
  stableService: ""
  canaryService: ""
  autoPromotionEnabled: true
  steps:
    - setWeight: 25
    - pause: {duration: 15s}
    - setWeight: 50
    - pause: {duration: 15s}
    - setWeight: 100
