replicaCount: 5

image:
  repository: nginx
  tag: latest

service:
  nodePort: 30083

rollout:
  strategy: canary
  autoPromotionEnabled: false   # MANUAL PROD APPROVAL
  steps:
    - setWeight: 5
    - pause: {}   # SRE approval
    - setWeight: 25
    - pause: {}
    - setWeight: 50
    - pause: {}
    - setWeight: 100
