replicaCount: 5
image:
  tag: latest
service:
  nodePort: 30083
rollout:
  strategy: canary
  steps:
    - setWeight: 25
    - pause: {duration: 15s}
    - setWeight: 50
    - pause: {duration: 15s}
    - setWeight: 100
