replicaCount: 3

image:
  repository: nginx
  tag: latest

service:
  nodePort: 30082

rollout:
  strategy: canary
  autoPromotionEnabled: false   # MANUAL PROMOTION in STAGE
  steps:
    - setWeight: 20
    - pause: {}        # WAIT FOR QA APPROVAL
    - setWeight: 50
    - pause: {}
    - setWeight: 100
